{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.koding.launcher",
    "module": "common",
    "version": "LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "common-LOCAL.jar",
          "url": "common-LOCAL.jar",
          "size": 30133,
          "sha512": "1adfec731481a9acc85405f83dae9c8256a79c82ab20abd94d8fa52b75c98fcbda43450b6beb180ad98902508ec89d58e899dddecea23c92c3e7d4b103dbae0f",
          "sha256": "864c54be3b7c124076690f5b7dea36e9a9231e1a4f1679a2736a224cd4279150",
          "sha1": "922c3de615f92dbd33003dd709048ba86f1cad05",
          "md5": "e124391ce7043376f5a6b1d7e9938e98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "common-LOCAL.jar",
          "url": "common-LOCAL.jar",
          "size": 30133,
          "sha512": "1adfec731481a9acc85405f83dae9c8256a79c82ab20abd94d8fa52b75c98fcbda43450b6beb180ad98902508ec89d58e899dddecea23c92c3e7d4b103dbae0f",
          "sha256": "864c54be3b7c124076690f5b7dea36e9a9231e1a4f1679a2736a224cd4279150",
          "sha1": "922c3de615f92dbd33003dd709048ba86f1cad05",
          "md5": "e124391ce7043376f5a6b1d7e9938e98"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-LOCAL-all.jar",
          "url": "common-LOCAL-all.jar",
          "size": 3900204,
          "sha512": "943583c07a31ecf1436e5341386161b57b48b072f81c376d51af99ec39ca12be763cea8e8aa488706cd94575ab7ec01af06acf36e4b18ea99027bac21bdbca13",
          "sha256": "af0e50fd255021431a334e07ed3262aa220ec2c307eb7e85033a09834105bcf5",
          "sha1": "358ae3f0e0e305085037ec64ee5da406da292b3c",
          "md5": "a24f6da6a2de05caf2f619cf761c8f91"
        }
      ]
    }
  ]
}
