{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.koding.launcher",
    "module": "common",
    "version": "LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-RC"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "common-LOCAL.jar",
          "url": "common-LOCAL.jar",
          "size": 75870,
          "sha512": "380ecef1c272c32f5714b8a074a80ee601b0b1489125a1d40d893a91cea9ff742305112a100cf23584c35c416bdd2a8abe5acb5aff850ea997136661f6df319f",
          "sha256": "da9d12553de524615550cbd16be03a7641dcf2e5f859c509f293c35dc104c0f4",
          "sha1": "2af308836add95e3883c91fd4a4a4b09b494c8b8",
          "md5": "e994683a6b40de3b0c698877fd57c1a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-RC"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "common-LOCAL.jar",
          "url": "common-LOCAL.jar",
          "size": 75870,
          "sha512": "380ecef1c272c32f5714b8a074a80ee601b0b1489125a1d40d893a91cea9ff742305112a100cf23584c35c416bdd2a8abe5acb5aff850ea997136661f6df319f",
          "sha256": "da9d12553de524615550cbd16be03a7641dcf2e5f859c509f293c35dc104c0f4",
          "sha1": "2af308836add95e3883c91fd4a4a4b09b494c8b8",
          "md5": "e994683a6b40de3b0c698877fd57c1a1"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-LOCAL-all.jar",
          "url": "common-LOCAL-all.jar",
          "size": 4508320,
          "sha512": "42091690c358df2c17241989f3f03b1aef9abe83a28c9af547c8577845f0294dac53cd5d9ff511658c4a840e8065b0bc13bdc60c3091bb8de356bd861129b1bf",
          "sha256": "8184d7a9c0c8d5e062bae65bcfb549915dc249d74ad30ff29dc01edb20ab05ca",
          "sha1": "662645cd3f6be413fc74d4c30d42fd3f3cd52bce",
          "md5": "6b7b8f1fd8e8c44f6dcc9d0802750074"
        }
      ]
    }
  ]
}
