{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.koding.launcher",
    "module": "bootstrap",
    "version": "LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "dev.koding.launcher",
          "module": "common",
          "version": {
            "requires": "LOCAL"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.0-alpha5"
          }
        }
      ],
      "files": [
        {
          "name": "bootstrap-LOCAL.jar",
          "url": "bootstrap-LOCAL.jar",
          "size": 26326,
          "sha512": "5f102289634f2452818f77bfb3809be83ec0d6ad8ff8c4ba33d2cd3e37ce0aa027b5883dd0509f0397e6a4187291a8ef67d095054acb3aaf700702bc98c19bef",
          "sha256": "bbcf72a23d910143a99ee8fb12d29e4ea4549493ab882320e2d69f54c01669bf",
          "sha1": "31b9d3452464ccfe7633e1ff76d9f7180f4ff9d6",
          "md5": "2b562b7ca3d623afe7f5d4deb1cd534b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "dev.koding.launcher",
          "module": "common",
          "version": {
            "requires": "LOCAL"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.0-alpha5"
          }
        }
      ],
      "files": [
        {
          "name": "bootstrap-LOCAL.jar",
          "url": "bootstrap-LOCAL.jar",
          "size": 26326,
          "sha512": "5f102289634f2452818f77bfb3809be83ec0d6ad8ff8c4ba33d2cd3e37ce0aa027b5883dd0509f0397e6a4187291a8ef67d095054acb3aaf700702bc98c19bef",
          "sha256": "bbcf72a23d910143a99ee8fb12d29e4ea4549493ab882320e2d69f54c01669bf",
          "sha1": "31b9d3452464ccfe7633e1ff76d9f7180f4ff9d6",
          "md5": "2b562b7ca3d623afe7f5d4deb1cd534b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bootstrap-LOCAL-all.jar",
          "url": "bootstrap-LOCAL-all.jar",
          "size": 4562778,
          "sha512": "b52e0b8d3c196543ea2915c0e9af7b125c885d29d0fd9143d0d6af59d2996f488c9f880e8d8db5e23f680b832c937ecaee2779465e2fe0e1cf66b44f685437f7",
          "sha256": "033d0c0f434dc4f7e701afa5e657f4126933806989ecc547e360ae88c3ca0952",
          "sha1": "5d9c34e1e3db0eb6f0a5608e1dee44ac6296d3fa",
          "md5": "21a26b47bb34317566580ff2ba928e8a"
        }
      ]
    }
  ]
}
